#This is a test

name: GitHub Actions Test
on: 
  workflow_dispatch: #the UI button only appears if this file exists on the master branch
  push:
    branches: [ migrate-to-github-actions]
  pull_request:
    branches: [ migrate-to-github-actions]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Unit Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'xenial' #using a specific distribution of jdk11 (was AdoptOpenJDK)
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Before Script
    - run: | #Setting up the SQLite database and Make
        sqlite3 -version
        make -version
        make clean-sqlite
        make sqlite-db-build
        make sqlite-db-populate
    - name: Script
    - run: "./gradlew test --tests=org.*"
    - name: After Success
    - run: | #jacocoTestReport is for testing code coverage, submits the last report to the link
        "./gradlew jacocoTestReport" 
        bash <(curl -s https://codecov.io/bash)

