name: GitHub Actions Migration
on: 
  workflow_dispatch: #the UI button only appears if this file exists on the master branch
  push:
    branches: [ migrate-to-github-actions]
  pull_request:
    branches: [ migrate-to-github-actions]
jobs:
  # Gradle-Wrapper-Validation:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v2
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt' #using a specific distribution of jdk11 (AdoptOpenJDK)
  #       #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
  #       #settings-path: ${{ github.workspace }} # location for the settings.xml file
  #   - name: Setup Gradle
  #     uses: gradle/gradle-build-action@v2
  #   - run: "gradle wrapper"
  #   - uses: gradle/wrapper-validation-action@v1
  Unit-Test:
    # needs: Gradle-Wrapper-Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' #using a specific distribution of jdk11 (AdoptOpenJDK)
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Setup Gradle Wrapper
      run: "gradle wrapper"
    - name: Validate Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Before Script
      run: | #Setting up the SQLite database and Make
        sqlite3 -version
        make -version
        make clean-sqlite
        make sqlite-db-build
        make sqlite-db-populate
    - name: Script
      run: "./gradlew test --tests=org.*"
    - name: After Success
      run: | #jacocoTestReport is for testing code coverage, submits the last report to the link
        "./gradlew jacocoTestReport" 
        bash <(curl -s https://codecov.io/bash)

